### ISSUE TITLE
팀간 기술리뷰 2팀 모여라!

### ISSUE THREAD

**Issue by SecretJuJu** [woowa-techcamp-2021/store-4#27]
#11 리뷰어 자동할당 스크립트 ( 이거 냠냠해가면 어떨까요!? )

**Comment by hwookim** [comment]
#25 [리뷰](https://github.com/woowa-techcamp-2021/store-4/pull/25#pullrequestreview-729251139)
#24 [리뷰](https://github.com/woowa-techcamp-2021/store-4/pull/24#pullrequestreview-729260241)

**Comment by SecretJuJu** [comment]
#26 리액트 라우터 컴포넌트

**Comment by chaeeun037** [comment]
[#26 리뷰](https://github.com/woowa-techcamp-2021/store-4/pull/26/files#r688271420)

**Comment by SecretJuJu** [comment]
<a href="https://github.com/woowa-techcamp-2021/store-4/pull/24/files/d8abbfc745b122759490d82d04398e2f579a4471..bf970bd94f5501e2205427a6e49d139fc922669b#r688277320"/>#리뷰</a>

**Comment by SecretJuJu** [comment]
[https://github.com/woowa-techcamp-2021/store-4/pull/25/files/de0f5d14c356f6aa0dd886cf6e95e8cdf33f32c7#r688279510](#25 리뷰)
