### ISSUE TITLE
5팀의 리뷰입니다. 👀

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/store-4#95]
### 5팀 입니다.

코드 리뷰를 위해 왔습니다. 🧐
잘 부탁드려요. :) 
 

여기다 남기면 될듯합니다. @kowoohyuk  @Kwongiseok  @ondal1997

**Comment by Kwongiseok** [comment]
[PR](https://github.com/woowa-techcamp-2021/store-4/pull/24#pullrequestreview-734687273)
[PR #67](https://github.com/woowa-techcamp-2021/store-4/pull/91)

**Comment by ondal1997** [comment]
https://github.com/woowa-techcamp-2021/store-4/pull/80#pullrequestreview-734689016

잘보고갑니다..!

**Comment by kowoohyuk** [comment]
[#29](https://github.com/woowa-techcamp-2021/store-4/pull/75/files#r692688178)

sort 처리는 나중에 참고해서 잘 사용하도록 하겠습니다!

❤️
